layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /blog/:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  - name: Film Rating Database System
    # description:
    web_url: https://scruffier-riding.000webhostapp.com/
    image_url: assets/img/projects/film-rating.png

github-repos:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    github-repos:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  github: appletreeisyellow
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: chunchunye
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: chunyellow
  # unsplash: your_username
  # vk: your_username
  website: https://www.chunchunye.com/
  # youtube: your_username

email_address: hello@chunchunye.com
