name: Build and deploy Jekyll site to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master, dev]
  # pull_request:
  #   branches: [master, dev]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
