name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  github-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.JEKYLL_GITHUB_TOKEN
 }}
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
